food = input("Name a food: ")
plant = input("Name a plant: ")
cooking = input("Name a method of cooking: ")
burned = input("What word describes burned food? ")
item = input("Name a household item: ")
print()
print("MENU")
print(cooking, food, "with", burned, plant, "on a bed of", item)