print("Getting to Know You!")
name = input("What's your name? ")
food = input("What's your favorite food? ")
music = input("What's your favorite music? ")
location = input("Where do you live? ")
print()
print("You are " + name + ".")
print("You're probably hungry for " + food + "...")
print("and you love dancing to " + music + " music in " + location + ".")
print("Have a great day!")